# Matrix addition

In [1]:
import numpy as np
# Initializing an array
x = np.array([[1, 1], [2, 2]])
y = np.array([[10, 10], [20, 20]])

In [2]:
x+y

array([[11, 11],
       [22, 22]])

In [3]:
np.add(x,y)

array([[11, 11],
       [22, 22]])

# Matrix multiplication

In [4]:
x = np.array([[1, 1], [2, 2]])

In [5]:
2*x

array([[2, 2],
       [4, 4]])

# Matrix arithmetic

In [6]:
# subtraction
x-y

array([[ -9,  -9],
       [-18, -18]])

In [7]:
x*y

array([[10, 10],
       [40, 40]])

In [8]:
# division
x/y

array([[ 0.1,  0.1],
       [ 0.1,  0.1]])

In [9]:
# exponential
x**y

array([[      1,       1],
       [1048576, 1048576]], dtype=int32)

# Matrix matrix multiplication

In [10]:
x=np.array([[1, 1], [2, 2]])
y=np.array([[10, 10], [20, 20]])

In [11]:
np.dot(x,y)

array([[30, 30],
       [60, 60]])

# Matrix transpose

In [12]:
# Initialize a matrix
A = np.array([[1,2],[3,4]])
A.transpose()

array([[1, 3],
       [2, 4]])

# Matrix inversion

In [13]:
from scipy import linalg

In [14]:
A = np.array([[1,2],[3,4]])

In [15]:
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Solving linear systems using matrices

In [16]:
from scipy import linalg

In [17]:
A=[[1,3,5],[2,5,1],[2,3,8]]
b=[[10],[8],[3]]

In [18]:
np.dot(linalg.inv(A),b)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [19]:
linalg.solve(A, b)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

# Determinant of a matrix

In [20]:
linalg.det(A)

-25.000000000000004

# Null space of a matrix

In [21]:
import sympy
M = sympy.Matrix([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])

In [22]:
M.nullspace()

[Matrix([
 [-15],
 [  6],
 [  1],
 [  0],
 [  0]]), Matrix([
 [0],
 [0],
 [0],
 [1],
 [0]]), Matrix([
 [   1],
 [-1/2],
 [   0],
 [   0],
 [   1]])]

In [23]:
x=[
[-15],
[  6],
[  1],
[  0],
[  0]]


In [24]:
np.dot(np.array(M),x)

array([[0],
       [0]], dtype=object)

# Range of a matrix

In [25]:
x=np.array([[1,100],[2,200]])

In [26]:
np.ptp(x)

199

In [27]:
np.ptp(x,axis=1)

array([ 99, 198])

In [28]:
np.ptp(x,axis=0)

array([  1, 100])

# Rank and nullity of a matrix

In [29]:
a=np.array([[3,2,-1],[2,-3,-5],[-1,-4,-3]])

In [30]:
np.linalg.matrix_rank(a)

2

In [31]:
a.shape[1]

3

In [32]:
a.shape[1] - np.linalg.matrix_rank(a) 

1

# LU decomposition of a matrix

In [33]:
A = np.array([[2., 1., 1.], [1., 3., 2.], [1., 0., 0.]])

In [34]:
import scipy.linalg as linalg

In [35]:
P, L, U = linalg.lu(A)

In [36]:
print(L)

[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]


In [37]:
print(U)

[[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]


In [38]:
np.dot(L,U)

array([[  2.00000000e+00,   1.00000000e+00,   1.00000000e+00],
       [  1.00000000e+00,   3.00000000e+00,   2.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,  -2.77555756e-17]])

# QR decomposition of a matrix

In [39]:
import scipy.linalg as linalg 
import numpy as np


In [40]:
A = np.array([ [2., 1., 1.], [1., 3., 2.], [1., 0., 0]])

In [41]:
Q, R = linalg.qr(A)

In [42]:
print(Q)

[[-0.81649658  0.27602622 -0.50709255]
 [-0.40824829 -0.89708523  0.16903085]
 [-0.40824829  0.34503278  0.84515425]]


In [43]:
print(R)

[[-2.44948974 -2.04124145 -1.63299316]
 [ 0.         -2.41522946 -1.51814423]
 [ 0.          0.         -0.16903085]]


In [44]:
print(np.dot(Q,Q.T))

[[  1.00000000e+00  -1.05102508e-17  -3.90671821e-17]
 [ -1.05102508e-17   1.00000000e+00   2.51394744e-17]
 [ -3.90671821e-17   2.51394744e-17   1.00000000e+00]]


In [45]:
print(np.dot(Q,R))

[[  2.00000000e+00   1.00000000e+00   1.00000000e+00]
 [  1.00000000e+00   3.00000000e+00   2.00000000e+00]
 [  1.00000000e+00   1.11022302e-16  -7.63527929e-17]]


# Eigenvalue and eigenvector of a matrix

In [46]:
a = np.array([[1, 2], [3, 4]])

In [47]:
la, v = linalg.eig(a)

In [48]:
print(la)

[-0.37228132+0.j  5.37228132+0.j]


In [49]:
print(v)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [50]:
np.dot(a,v)

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [51]:
np.dot(la,v)

array([ 3.34643208+0.j, -4.73056832+0.j])

# Diagonalizing a matrix

In [52]:
import numpy as np

In [53]:
a= np.array([1,2,3])

In [54]:
A=np.diag(a)
print(A)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [55]:
la, v = linalg.eig(A)
print(la)
print(v)


[ 1.+0.j  2.+0.j  3.+0.j]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [56]:
a = np.array([[1, 2,0], [2,1,0],[0,0,-3]])
la, v = linalg.eig(a)
print(la)
print(v)

[ 3.+0.j -1.+0.j -3.+0.j]
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [57]:
np.dot(np.dot(np.linalg.inv(v),a),v)

array([[  3.00000000e+00,   4.44089210e-16,   0.00000000e+00],
       [  6.66133815e-16,  -1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,  -3.00000000e+00]])

In [58]:
np.diag(la)

array([[ 3.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -3.+0.j]])

In [59]:
np.dot(np.dot(np.linalg.inv(v),a),v)-np.diag(la)

array([[ -4.44089210e-16+0.j,   4.44089210e-16+0.j,   0.00000000e+00+0.j],
       [  6.66133815e-16+0.j,  -4.44089210e-16+0.j,   0.00000000e+00+0.j],
       [  0.00000000e+00+0.j,   0.00000000e+00+0.j,   0.00000000e+00+0.j]])

# Jordan form of a matrix

In [60]:
import numpy as np
from sympy import Matrix



In [61]:
a = np.array([[5, 4, 2, 1], [0, 1, -1, -1], [-1, -1, 3, 0], [1, 1, -1, 2]])

In [62]:
m = Matrix(a)

In [63]:
P, J = m.jordan_form()

In [64]:
J

Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 4, 1],
[0, 0, 0, 4]])

# SVD of a matrix

In [65]:
a = np.array([[1, 2], [3, 4]])

In [66]:
from scipy import linalg

In [67]:
linalg.svd(a)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([ 5.4649857 ,  0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [68]:
U = np.array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]])
sigma = np.array([[ 5.4649857 ,  0],
                  [0,0.36596619]])
V=np.array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]])


In [69]:
np.dot(np.dot(U,sigma),V)

array([[ 0.99999999,  1.99999998],
       [ 3.00000003,  4.00000001]])

# Sparse matrix

In [70]:
import numpy as np
from scipy import sparse


In [71]:
A = np.array([[1,2,0],[0,0,3],[1,0,4]])

In [72]:
sA = sparse.csr_matrix(A)

In [73]:
print(sA)

  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	1
  (2, 2)	4


In [74]:
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import spsolve
from numpy.linalg import solve, norm
from numpy.random import rand



In [75]:
A = lil_matrix((10000, 10000))

In [76]:
A[0, :100] = rand(100)
A[1, 100:200] = A[0, :100]


In [77]:
A.setdiag(rand(10000))

In [78]:
b = rand(10000)

In [79]:
A = A.tocsr()

In [80]:
x = spsolve(A, b)

In [83]:
import time
start_time=time.time()
x = spsolve(A.tocsr(), b)
end_time=time.time()
print(end_time-start_time)

0.00500035285949707


In [84]:
import time
start_time=time.time()
x = solve(A.toarray(), b)
end_time=time.time()
print(end_time-start_time)

6.414999961853027
